[general]
board = "uno"

# ravedude should open a serial console after flashing
open-console = true
serial-baudrate = 57600

# The serial port to use. If not set, ravedude will try to find the port automatically.
port = "/dev/ttyACM0"
