[build]
target = "avr-none"
rustflags = ["-C", "target-cpu=atmega328"]

[unstable]
build-std = ["core"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude duemilanove --open-console --baudrate 57600 --port /dev/ttyUSB0"
