[package]
name = "srxl2"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "srxl2"
test = false
bench = false

[features]
default = ["no_std"]
no_std = []

[dependencies]
zerocopy = { version = "0.8.23", features = ["derive"] }
